#!/bin/bash
APP_NAME=$1
if [ -z "$APP_NAME" ]; then
  echo "Usage: ./scripts/generate-app.sh [AppName]"
  exit 1
fi

LOWER=$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]')
DIR="packages/app/generated/$LOWER"

mkdir -p "$DIR"

cat > "$DIR/page.tsx" << EOF
// [Architect]: Generated by StructAI Orchestrator
// SwiftUI-style layout — SF Design System applied
import { SFView, SFLargeTitle, SFCard } from '@/components/sf-ui'

export default function ${APP_NAME}Page() {
  return (
    <SFView>
      <SFLargeTitle>${APP_NAME}</SFLargeTitle>
      <SFCard>
        {/* [Coder]: Implement feature content here */}
      </SFCard>
    </SFView>
  )
}
EOF

cat > "$DIR/types.ts" << EOF
// [Architect]: ${APP_NAME} Type Contracts
export interface ${APP_NAME}State {
  isLoading: boolean
  error: string | null
}
EOF

echo "✅ App '$APP_NAME' scaffolded in $DIR"
echo "👉 Nächster Schritt: Cursor Composer mit [Coder] Prompt öffnen"
